<a href="https://colab.research.google.com/github/hariiomupadhyay/neural-network/blob/main/Logic_Gates.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

def simple_alu(operand1, operand2, operation):
    if operation == "add":
        return tf.add(operand1, operand2)
    elif operation == "subtract":
        return tf.subtract(operand1, operand2)
    elif operation == "and":
        return tf.logical_and(operand1, operand2)
    elif operation == "equal":
        return tf.equal(operand1, operand2)
    else:
        raise ValueError("Unsupported operation")

# Example usage
a = tf.constant([1, 2, 3], dtype=tf.int32)
b = tf.constant([4, 1, 3], dtype=tf.int32)
c = tf.constant([True, False, True], dtype=tf.bool)
d = tf.constant([False, False, True], dtype=tf.bool)

sum_result = simple_alu(a, b, "add")
equal_result = simple_alu(c, d, "equal")

print("Sum:", sum_result.numpy())
print("Equality:", equal_result.numpy())

Sum: [5 3 6]
Equality: [False  True  True]


In [ ]:
import tensorflow as tf

# Define the input tensors for the AND gate
A = tf.constant([False, False, True, True], dtype=tf.bool)
B = tf.constant([False, True, False, True], dtype=tf.bool)

# Implement the AND gate using the TensorFlow logical and function
Z = tf.math.logical_and(A, B)

# Print the output tensor
print(Z)

tf.Tensor([False False False  True], shape=(4,), dtype=bool)


In [ ]:
import tensorflow as tf

# Define the input tensors for the NOT gate
A = tf.constant([False, True], dtype=tf.bool)

# Implement the NOT gate using the Tensor Flow logical not function
Z = tf.math.logical_not(A)

# Print the output tensor
print(Z)

tf.Tensor([ True False], shape=(2,), dtype=bool)


In [ ]:
import tensorflow as tf
# Define the input tensors for the OR gate
A = tf.constant([False, False, True, True], dtype=tf.bool)
B = tf.constant([False, True, False, True], dtype=tf.bool)

# Implement the OR gate using the Tensor Flow logical or function
Z = tf.math.logical_or(A, B)

# Print the output tensor
print(Z)

tf.Tensor([False  True  True  True], shape=(4,), dtype=bool)


In [ ]:
import tensorflow as tf

# Define input tensors for NOR gate
A = tf.constant([False, False, True, True], dtype=tf.bool)
B = tf.constant([False, True, False, True], dtype=tf.bool)

# Implement NOR gate: NOT(OR(A,B))
Z = tf.math.logical_not(tf.math.logical_or(A, B))

# Print output tensor
print(Z)

tf.Tensor([ True False False False], shape=(4,), dtype=bool)


In [ ]:
import tensorflow as tf

# Define the input tensors for the XOR gate
A = tf.constant([False, False, True, True], dtype=tf.bool)
B = tf.constant([False, True, False, True], dtype=tf.bool)

# Implement the XOR gate using the TensorFlow logical_xor function
Z = tf.math.logical_xor(A, B)

# Print the output tensor
print(Z)

tf.Tensor([False  True  True False], shape=(4,), dtype=bool)


In [ ]:
import tensorflow as tf

# Define the input tensors for the XNOR gate
A = tf.constant([False, False, True, True], dtype=tf.bool)
B = tf.constant([False, True, False, True], dtype=tf.bool)

# Implement the XNOR gate using TensorFlow logical_xor and logical_not functions
# First, implement the XOR Gate between A and B
Z = tf.math.logical_xor(A, B)

# Now implement the NOT Gate on the output of the XOR GATE (Z) to get XNOR
Y = tf.math.logical_not(Z)

# Print the output tensor
print(Y)

tf.Tensor([ True False False  True], shape=(4,), dtype=bool)


In [ ]:
import tensorflow as tf

# 1. Define the training data (NAND gate truth table)
A = tf.constant([False, False, True, True], dtype=tf.bool)
B = tf.constant([False, True, False, True], dtype=tf.bool)

# Implement the NAND gate using TensorFlow logical_and and logical_not functions
Z = tf.math.logical_not(tf.math.logical_and(A, B))

# Print the output tensor
print(Z)

tf.Tensor([ True  True  True False], shape=(4,), dtype=bool)


In [ ]:
import tensorflow as tf

# Selection lines (S2, S1, S0)
S2 = tf.constant([False, False, False, False, True, True, True, True], dtype=tf.bool)
S1 = tf.constant([False, False, True, True, False, False, True, True], dtype=tf.bool)
S0 = tf.constant([False, True, False, True, False, True, False, True], dtype=tf.bool)

# Data inputs (D0-D7).
D0 = tf.constant([True, True, True, True, True, True, True, True], dtype=tf.bool)
D1 = tf.constant([False, False, False, False, False, False, False, False], dtype=tf.bool)
D2 = tf.constant([True, False, True, False, True, False, True, False], dtype=tf.bool)
D3 = tf.constant([False, True, False, True, False, True, False, True], dtype=tf.bool)
D4 = tf.constant([True, True, False, False, True, True, False, False], dtype=tf.bool)
D5 = tf.constant([False, False, True, True, False, False, True, True], dtype=tf.bool)
D6 = tf.constant([True, False, False, True, True, False, False, True], dtype=tf.bool)
D7 = tf.constant([False, True, True, False, False, True, True, False], dtype=tf.bool)


